databases:
  - name: tausidb
    plan: free

services:
  - type: web
    name: tausi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tausi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tausidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
