# Generated by Django 5.2.2 on 2025-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('package', models.CharField(choices=[('Luxury Safari', 'Luxury Safari'), ('Coastal Retreat', 'Coastal Retreat'), ('Mount Kenya Trek', 'Mount Kenya Trek'), ('Nairobi City Experience', 'Nairobi City Experience'), ('Amboseli Adventure', 'Amboseli Adventure')], max_length=50)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
